### ISSUE TITLE
add functionality to subcriber robotling telemetry messages from broker

### ISSUE THREAD

**Issue by greenbase** [teuler/robotling#1]

**Comment by teuler** [comment]
Hi, not sure what your suggest/request is. Could you provide some details?

**Comment by greenbase** [comment]
Hello,

Unfortunately I realized to late that this doesn’t belong there. I’m sorry for that.

Git and GitHub is still rather new to me and and I was wondering whether I could 
Organize my To-do’s that way.

By the way, thanks for this great project! I build six robotlings last year, which are now used for education purposes at my university.

Sincerely

Daniel Mansfeldt


Von: Thomas Euler
Gesendet: Sonntag, 9. August 2020 16:35
An: teuler/robotling
Cc: GreenCap95; Author
Betreff: Re: [teuler/robotling] add functionality to subcriber robotlingtelemetry messages from broker (#1)

Hi, not sure what your suggest/request is. Could you provide some details?

**Comment by teuler** [comment]
Hi Daniel,

thanks for your message and for liking the project.

Best
Thomas
